---
title: "Introduction to main functions"
date: today
vignette: >
  %\VignetteIndexEntry{Introduction to main functions}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The `comprehensivecohort` package provides tools for analyzing data from comprehensive cohort studies in the presence of unmeasured confounding and missing outcome (either continuous or binary). The goal is to estimate the comprehensive cohort causal effects (CCCE), the average causal effect for the entire cohort. The vignette has two parts: 1). Methodologies. This part will cover details on what is comprehensive cohort study design, the causal estimands, assumptions, and brief description of the estimation process. 2). Implementation. This part will focus on how to use the R functions to implement the estimation of CCCE under pre-specified sensitivity parameters. We will also provide codes for results. 

# Methodologies

## Comprehensive cohort study design

## Causal estimands

## Assumptions

## Methods

# Implementation

## Data

## Results








